name: "SCP File Transfer"
description: "Upload and download files via SCP."
author: "Nicklas Frahm"
inputs:
  direction:
    description: "transfer direction"
    required: yes
  source:
    description: "source files to copy"
    required: yes
  target:
    description: "target folder"
    default: "."
  timeout:
    description: "timeout for ssh connections"
    default: "30s"
  action_timeout:
    description: "timeout for action"
    default: "10m"
  host:
    description: "ssh host"
    required: yes
  port:
    description: "ssh port"
    default: "22"
  username:
    description: "ssh username"
    default: "root"
  insecure_password:
    description: "ssh password"
    default: ""
  key:
    description: "content of ssh private key. ex raw content of ~/.ssh/id_rsa"
    required: yes
  fingerprint:
    description: "sha256 fingerprint of the host public key"
    required: yes
  proxy_host:
    description: "ssh proxy host"
  proxy_port:
    description: "ssh proxy port"
    default: "22"
  proxy_username:
    description: "ssh proxy username"
    default: "root"
  insecure_proxy_password:
    description: "ssh proxy password"
    default: ""
  proxy_key:
    description: "content of ssh proxy private key. ex raw content of ~/.ssh/id_rsa"
  proxy_fingerprint:
    description: "sha256 fingerprint of the proxy host public key"

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    DIRECTION: ${{ inputs.direction }}
    SOURCE: ${{ inputs.source }}
    TARGET: ${{ inputs.target }}
    TIMEOUT: ${{ inputs.timeout }}
    ACTION_TIMEOUT: ${{ inputs.action_timeout }}
    HOST: ${{ inputs.host }}
    PORT: ${{ inputs.port }}
    USERNAME: ${{ inputs.username }}
    INSECURE_PASSWORD: ${{ inputs.insecure_password }}
    KEY: ${{ inputs.key }}
    FINGERPRINT: ${{ inputs.fingerprint }}
    PROXY_HOST: ${{ inputs.proxy_host }}
    PROXY_PORT: ${{ inputs.proxy_port }}
    PROXY_USERNAME: ${{ inputs.proxy_username }}
    INSECURE_PROXY_PASSWORD: ${{ inputs.insecure_proxy_password }}
    PROXY_KEY: ${{ inputs.proxy_key }}
    PROXY_FINGERPRINT: ${{ inputs.proxy_fingerprint }}

branding:
  icon: "copy"
  color: "gray-dark"
